# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.Scenario'),
        ),
    ]
