# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20160409_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='misinf',
            field=models.BooleanField(default=False),
        ),
    ]
