# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_event_misinf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
