# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='location',
            field=models.ManyToManyField(to='editor.Location'),
        ),
    ]
