# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160407_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='acttarget',
            field=models.IntegerField(default=-1),
        ),
    ]
