# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20160419_1832'),
        ('game', '0007_auto_20160426_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misinformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Event')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
    ]
