# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_misinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameOver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='caughtKeyCharacter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='numOfLivingAgents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='researchedThisTurn',
            field=models.BooleanField(default=False),
        ),
    ]
